### ISSUE TITLE
Shortcuts do not work on all tabs

### ISSUE THREAD

**Issue by skontar** [pmalecka/chrome-shortkeys#14]
I have tried to set `Alt+down` and `Alt+up` fro next/previous tab. It works usually, but does not work on Addons tab or New (empty) tab.

**Comment by pmalecka** [comment]
Yup, this is correct, I'll update the addon description on AMO. The thing is that due to the way the API is setup on Firefox - the addon only works in a context of a webpage. Pages like about:newtab, about:addons or any other internal pages do not allow the WebExt to execute (security policy, same as in chrome). We are waiting for a new API to solve these issues.

**Comment by Luke-Baker** [comment]
> We are waiting for a new API to solve these issues.

Is that [bug 1411795](https://bugzilla.mozilla.org/show_bug.cgi?id=1411795) or another one?
Thanks in advance.

**Comment by Luke-Baker** [comment]
[Pin Unpin Tab 2.0](https://addons.mozilla.org/firefox/addon/pinunpin-tab/) has no issue getting its keyboard shortcut to work on about:addons, about:blank, when the location bar is focused, or any of the other situations you claim are due to lacking API support in Firefox.
